### ISSUE TITLE
Suppress debug output

### ISSUE THREAD

**Issue by lydonjj** [thomastu/pyEIA#16]
Running the code automatically outputs a debug post to the command line, how can I suppress it? 

Example: 2020-11-04 21:01:25.993 | DEBUG    | eia.api.base:_post:63 - made POST to https://api.eia.gov/series/ with parameters {'api_key': 'SECRET_APIKEY', 'out': 'json'} and payload
{'series_id': 'ELEC.SALES.AK-IND.M'}

Looks like it is in the _get_data method when you use Post? 

Thank you!

**Comment by thomastu** [comment]
Thanks, previously generated logging messages were being configured implicitly via `loguru`.  I've just pushed up a small fix (0.1.4) that addresses this (`pip install --upgrade pyeia`) should fix this.  The library now (in line with the python logging cookbook) requires any downstream applications to enable library-level logging explicitly to see library logs.
